### ISSUE TITLE
UVOZ tabele 3

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#10]
Želim uvozit tretjo tabelo, ker jo potrebujem iz spletne strani
https://en.wikipedia.org/wiki/List_of_U.S._states_by_GDP_per_capita

napisala sem uvoz kot pri prejšnji, vendar mi sploh ne uvozi te tabele, ki jo želim ampak čisto neki drugega

To uvoženo tabelo bi rada preuredila tako, da izračunam povprečni BDP od vseh ostalih let (dodaten stolpec povprečje) in potem naredim primerjavo s stopnjo smrti iz tabele1(zadnji stolpec) samo za tista mesta, ki se pojavijo v obeh tabelah (tabelaBDP in tabela1)...dobila bi potem neko novo tabelo.
kako bi to naredila lahko.

**Comment by jaanos** [comment]
Ko definiraš `tabelaBDP`, namesto `stran` uporabi `stran1`, sicer ti uporabi podatke iz prejšnjega uvoza. Pri `html_table` bo treba podati še parameter `fill = TRUE`, saj ponekod manjka zadnji stolpec.

**Comment by valentina2pucer** [comment]
am kako  pa naj popravim števila oz pisavo znake..glede na to da sem dala da naj  bo utf-8

**Comment by jaanos** [comment]
Najlažje bo, če v prvih dveh stolpcih ohraniš samo števila oziroma črke in presledke, v ostalih stolpcih pa odstraniš vejice:

``` R
tabelaBDP$Rank <- tabelaBDP$Rank %>% strapplyc("([0-9]+)") %>% as.numeric()
tabelaBDP$State <- tabelaBDP$State %>% strapplyc("([a-zA-Z ]+)")
tabelaBDP[-c(1,2)] <- apply(tabelaBDP[-c(1,2)], 2,
                            . %>% {gsub(",", "", .)} %>% as.numeric())
```

**Comment by valentina2pucer** [comment]
In kako bi js zdej nardila, da mi v tabeliBDP pobriše vse vrstice glede na državo, ki se ne nehaja v 
tabeli  nesrece pod Lokacija, glede na to da je tam več mest oz držav..

**Comment by jaanos** [comment]
Podatkov ti ni nujno potrebno brisati - bo pa sicer treba nekoliko popraviti uvoz, da bo delovalo združevanje z drugimi tabelami. Da bodo v razpredelnici ostale iste zvezne države, kot jih imaš npr. v `capitals`, po pretvorbi prvega stolpca v števila lahko izpustiš tiste vrstice, ki imajo v prvem stolpcu `NA` (razen `"District of Columbia"`, ki se pojavi v `capitals`:

``` R
tabelaBDP <- tabelaBDP %>%
  filter(!is.na(Rank) | grepl("District of Columbia", State))
```

Tukaj funkcija `grepl` deluje tako kot `grep`, le da namesto številskega vektorja vrne logični vektor. Tako lahko to funkcijo uporabiš za filtriranje po vsebini nizov v stolpcih.

Sedaj lahko popraviš pretvorbo zveznih držav. Ker `strapplyc` vrne seznam, ga bo treba pretvoriti v vektor; da kasneje ne bo opozoril, lahko narediš iz njega še faktor:

``` R
tabelaBDP$State <- tabelaBDP$State %>% strapplyc("([a-zA-Z ]+)") %>%
  unlist() %>% factor()
```

Ostale stolpce lahko potem pretvoriš kot prej.

Sedaj (oziroma po potrebi, npr. pri risanju grafa) lahko dobljeno tabelo pridružiš obstoječi, kjer imaš države, npr. k `zdruzena.tabela` (ki je bila dobljena z združevanjem s `capitals`):

``` R
zdruzena.BDP <- inner_join(zdruzena.tabela, tabelaBDP)
```

Ker imata obe razpredelnici stolpec `State`, bo tega `inner_join` uporabil za združevanje. Sedaj imaš za vsako vrstico iz `zdruzena.tabela` zraven še podatke iz ustrezne vrstice iz `tabelaBDP`. Zvezne države, ki se pojavijo samo v `tabelaBDP`, se v novi razpredelnici ne bodo pojavile.

**Comment by valentina2pucer** [comment]
Pri tej tabeli bi dodala stolpec povprečja vseh let za vsako vrtico.. nekaj sem poskušala z zankami, ker
ne vem kako bi z mean funkcijo to napisala,..ne deluje

**Comment by jaanos** [comment]
Povprečje po vrsticah lahko izračunaš z `apply`, npr.

``` R
tabelaBDP$MeanBDP <- apply(tabelaBDP[c(3:8)], 1, mean, na.rm = TRUE)
```

Če se le da, se zank izogibaj.

**Comment by valentina2pucer** [comment]
ne deluje..se zaustavi že pri :
tabelaBDP <- tabelaBDP %>%
  filter(!is.na(Rank) | grepl("District of Columbia", State))

**Comment by jaanos** [comment]
Tole bi morala imeti že prej, namesto vrstice 95:

``` R
tabelaBDP$State <- tabelaBDP$State %>% strapplyc("([a-zA-Z ]+)") %>%
  unlist() %>% factor()
```

Na koncu ne rabiš `attach` in `detach` ter še enega klica `data.frame`, saj z vrstico 107 že dodaš nov stolpec v razpredelnico.
