### ISSUE TITLE
težava

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#11]
ne morem naložiti to kar sem naredila, ker mi je ponolno prišlo do konflikta ki sem ga razrešila in nevem zakaj mi noče ...

To git@github.com:valentina2pucer/APPR-2015-16.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:valentina2pucer/APPR-2015-16.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

ko komitam pa:
fatal: You are in the middle of a merge -- cannot amend.

**Comment by jaanos** [comment]
Očitno imaš pri commitu (pod sporočilom) obkljukano _Amend previous commit_. To odznači, potem bi moralo commitat. Potem naredi pull (saj očitno zadnje spremembe z GitHuba še nimaš pri sebi), po potrebi spet reši konflikte, potem pa push.
