### ISSUE TITLE
poročilo

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#12]
Kako naj vključim zemljevid v poročilo, ki ga imam pod vizualizacijo?

**Comment by jaanos** [comment]
Na isti način kot ostale grafe - najprej pokliči program `vizualizacija/vizualizacija.r` (lahko kar takoj za tem, ko kličeš `libraries.r` in `uvoz.r`), nato pa premakni izrisovanje zemljevida (ukaz `ggplot() + ...`) na mesto v poročilu, kjer ga želiš izrisati. Vrstico `print(zem)` izpusti, saj ti ta izpiše razpredelnico `zem` (in ne zemljevida).
