### ISSUE TITLE
tidy data

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#13]
zanima me, če je moja tabela npr.nesrece..to je urejena kot ty,dat.?
npr če pogledam po letnicah imam najprej vsa leta 2015 na zač.
al kako morem ti gledat?

**Comment by jaanos** [comment]
Razpredelnica `nesrece` je v obliki tidy data - za spremenljivko `Dogodek` so ostali stolpci meritve. Razpredelnica ne bi bila v tej obliki, če bi imela več stolpcev z istim podatkom za več različnih spremenljivk (npr. stolpci s podatkom za vsako leto posebej - to bi pretvorila tako, da bi iz vsakega stolpca naredila več vrstic, eno za vsako leto).
