### ISSUE TITLE
tabela

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#14]
kako bi jaz pri tabela_1, ki jo želim ustvariti iz nekaterih stolpcev prejšnjih dveh združila, saj niso enakih velikosti.

**Comment by jaanos** [comment]
Razpredelnici želiš najbrž združiti po zvezni državi. Ker pa je teh lahko več v vsaki vrstici razpredelnice `nesrece`, bo treba (podobno kot pri zemljevidu) te vrstice "razmnožiti". Potem lahko razpredelnici združiš z `inner_join`:

``` R
nesrece$Row <- 1:nrow(nesrece)
tabela_1 <- lapply(tabelaBDP$State, function(x) {
    r <- grep(x, nesrece$Lokacija)
    return(data.frame(State = rep(x, length(r)), Row = r))
  }) %>% bind_rows() %>% as.data.frame() %>%
  inner_join(nesrece, by = "Row") %>%
  inner_join(tabelaBDP, by = "State") %>%
  select(Lokacija = State, Stopnja_skode, PovprecjeBDP)
```

Dobljena razpredelnica bo imela po eno vrstico za vsak par nesreče in zvezne države, kjer se slednja pojavi v stolpcu `Lokacija` pri nesreči.

**Comment by valentina2pucer** [comment]
ponavljajoče vrstice glede na ime lokacije bi želela odstraniti..poskušala sem z funkcijo duplicated
zakaj vrne logical(0)..ali ne vrne seznama true false..itd.kjer se ponavlja neka vrednost?

**Comment by jaanos** [comment]
Tako, `duplicated` vrne vektor, ki je `TRUE` za vsako ponovljeno vrednost (tj., `FALSE` ob prvi pojavitvi in `TRUE` ob vsaki naslednji pojavitvi posamezne vrednosti). Na čem pa kličeš to funkcijo? Preveri, ali ji morda ne podaš prazne razpredelnice oziroma vektorja.

**Comment by jaanos** [comment]
Aha, vidim, kaj je narobe - uporabiti želiš razpredelnico `tabela_1` (s podčrtajem).

**Comment by valentina2pucer** [comment]
in kaj moram potem spremeniti.?ali ne morem tega narediti na tabela_1?

**Comment by jaanos** [comment]
Lahko samo pravo ime spremenljivke uporabi (v vrsticah 124 do 126).

**Comment by valentina2pucer** [comment]
sem spremenila, vendar je še vedno nekaj narobe  z vrsticami in nevem kako naj napako odpravim

**Comment by jaanos** [comment]
Takole bi šlo:

``` R
tabela_1 <- tabela_1[!duplicated(tabela_1$Lokacija),]
```

Vendar pa si tukaj zavrgla nekatere podatke. Vsaka vrstica v `tabela_1` namreč ustreza eni nesreči, ki zajema navedeno državo - seveda je tudi stopnja škode lahko za vsako nesrečo različna. S takim odstranjevanjem vrstic ohraniš podatek za samo eno nesrečo v vsaki državi - ne veš pa, katero.
