### ISSUE TITLE
tabela_2

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#15]
podobno kot tabelo tabela_1, želim združiti dve tabeli, da dobim tabelo_2.nekaj se mi ne ujema v obsegu podatkov..kaj moram popraviti.?

**Comment by jaanos** [comment]
Najprej se tukaj vprašaj, kaj natanko želiš narediti. Izgleda, kot da nesreče v razpredelnici `nesrece` niso iste kot tiste iz `tabela1`, tako da je tako združevanje v bistvu nesmiselno.

**Comment by valentina2pucer** [comment]
tukaj želim pnovno glede na lokacijo , ki se nahaja pri obeh tabelah dodati ta stolpec za stopnjo smrti in takodobiti novo tabelo

**Comment by jaanos** [comment]
Stopnja smrti je vezana na posamezno nesrečo, tako kot stopnja škode (glej #14). Če bi združevala samo glede na lokacijo, nimaš informacije, za katero nesrečo gre - najverjetneje boš dobila podatke od dveh različnih nesreč.

**Comment by valentina2pucer** [comment]
kako bi to potem združila..ker bi rada primerjalate tri stvari...da potem vem ali moja predpostavka velja ali pa jo ovržem.. ali je bolje če gledam vsako stvar posebej z BDP?..ker sem namerava pogledat ali je tudi stopnja smrti z stopnjo skode kaj pvezano ..in potem to prikazat še z grafi..ipd..

**Comment by jaanos** [comment]
Najbolje bo, da tudi stopnjo smrti izpelješ iz razpredelnice `nesrece` - navsezadnje imaš v `tabela1` samo podmnožico nesreč iz prejšnje razpredelnice, ki so razporejene po številu žrtev. Potem lahko za vsako nesrečo pridobiš BDP zvezne države (ali več njih), kjer se je zgodila, in primerjaš te podatke (torej se ne omejiš na eno nesrečo na zvezno državo).

**Comment by valentina2pucer** [comment]
v tabelo nesrece sem dodala stolpec s stopnjo smrti, vendar mi ne upošteva pogojev (večidel veliko)...zakaj ne dela pavilno?
in sm dodala z enako kodo kot stopnjo skode, vendar mi samo nadmestilo..kako popravim da dam obadva?

**Comment by jaanos** [comment]
V stolpcu `Smrtne.žrtve` imaš nize. Potrebno se bo znebiti še nekaj primerov, ko imaš niz tipa od-do, in preostale številke pretvoriti v številski tip, preden kaj delaš z njimi.

**Comment by valentina2pucer** [comment]
to zapišem nekje v tej kodi ,ko združujem?
pač kot as.numeric. al preden dam skupaj to?

**Comment by jaanos** [comment]
To naredi že prej, ko urejaš stolpce razpredelnice `nesrece`, da bodo pri združevanju števila na voljo kot taka. Preden uporabiš `as.numeric`, seveda poskrbi še za tiste vrednosti, ki niso števila.

**Comment by valentina2pucer** [comment]
kako naj to nardim...sedaj sem dala vejico namesto - in bi mogla dobit recimo povprečje (mean) in bi s tem nadomestila.. kako naj to napišem da mi upošteva samo pri teh kjer se pojavi ta dvojni podatek..sem provala dat v list ampak ne deluje

**Comment by jaanos** [comment]
Lahko narediš tako:

``` R
nesrece$Smrtne.žrtve <- nesrece$Smrtne.žrtve %>%
  strapplyc("([0-9]+)") %>% lapply(as.numeric) %>%
  lapply(mean) %>% unlist()
nesrece$Smrtne.žrtve[is.nan(nesrece$Smrtne.žrtve)] <- NA
```

Iz vsakega niza pobereš vsa števila (dobiš seznam znakovnih vektorjev), ta pretvoriš z `as.numeric`, nato pa izračunaš povprečje - kjer je samo ena številka, bo ta ostala, kjer sta pa dve, bo dejansko izračunalo povprečje. Kjer ni števil, dobi `mean` prazen vektor in tam vrne `ǸaN` - te je potem potrebno nadomestiti z `NA`.

**Comment by valentina2pucer** [comment]
kako pa naj nardim ko združujem , da bo oboje v tabela_1..,ker mi samo eno stvar da potem

**Comment by jaanos** [comment]
Sedaj dvakrat definiraš `tabela_1`, tako da na koncu obvelja zadnja definicija. Če hočeš imeti več stolpcev, jih enostavno navedi znotraj `select`.
