### ISSUE TITLE
analiza

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#16]
Pod analiza bi rada naredila histogram glede na tabelo_1.
Zanima me, kako naj v enem histogramu s stolpci prikažem BDP. Zdi se mi,da mi stolpce napačno prikaže.

**Comment by jaanos** [comment]
Ukaz `hist` ni del knjižnice ggplot2 in z njim ne moreš uporabiti funkcije `aes`. Poleg tega ti histogram zbere podatke v skupine in prikaže velikosti posameznih skupin, kar najbrž ni to, kar hočeš.

Stolpčni diagram povprečnih BDP po državah lahko narišeš npr. tako:

``` R
ggplot(tabela_1, aes(x = Lokacija, y = PovprecjeBDP)) +
  geom_bar(stat = "identity") + xlab("Lokacija") +
  ggtitle("Ali je povezava med stopnjo škode in smrti s povprečnim BDP lokacije?") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) # zavrtimo besedilo
```

Seveda bo koristno, da deliš vrednosti na osi y npr. s 1000, da na grafu ne bodo prikazane vrednosti v eksponentni notaciji. Potem lahko z `ylab` nastaviš oznako osi y, kjer poveš, da gre za tisoče dolarjev.

**Comment by valentina2pucer** [comment]
kako naj vključim graf za oba stolpca od stopenj ?...tisto kar mam zakomentirano sem provala dodat

**Comment by jaanos** [comment]
Kaj natančno hočeš prikazati? Izgleda, da hočeš stopnjo škode in smrti prikazati s črto - kako naj bi ta črta potekala?

Sicer pa opažam, da imaš v `tabela_1` že združene podatke, tako da se lahko vsaka država pojavi večkrat. Za zgornjih stolpčni diagram bo tako treba uporabiti razpredelnico `tabelaBDP`.

Če hočeš prikazati npr. korelacijo med BDP in škodo, bo bolje, da narediš graf, ki bo ta podatka prikazoval na oseh x in y. Še bolje bo, če namesto stopnje prikažeš kar konkretno številko.

**Comment by valentina2pucer** [comment]
aja narobe sem razmišljala......ja pač zdej sem dala konkretne številke.. in bi da mi dva grafa čez nariše glede na tiste podatke..nevem točno kako to napisat..nekaj sem si pomagala z internetom, vendar ne deluje..

**Comment by jaanos** [comment]
Najprej, ukaza `plot` in `lines` nista del knjižnice ggplot2, tako da ju ne moreš uporabljati skupaj z `ggplot`. Poleg tega v  `tabela_1` nimaš stolpcev `Škoda` in `Smrtne.žrtve` - dodaj ju tam, kjer to razpredelnico definiraš.

Kaj točno misliš s tem, da bi ti grafa narisalo čez? Lestvice so namreč različne, poleg tega pa imaš lahko za posamezno zvezno državo lahko več nesreč. Lahko bi sicer naredila nekaj takega:

``` R
ggplot(tabela_1, aes(x = Lokacija, y = PovprecjeBDP/1000)) +
  # position = "dodge": stolpci za isto državo so en zraven drugega (da ne bodo prikazani BDP-ji večji v državah z več nesrečami)
  geom_bar(stat = "identity", position = "dodge") +
  # position = "jitter": naključno zamaknemo pike, da bodo podobne vrednosti bolje vidne
  geom_point(aes(y = Škoda/1e9), position = "jitter") +
  ggtitle("Ali je povezava med stopnjo škode in smrti s povprečnim BDP lokacije?") +
  xlab("Lokacija") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```

Tukaj je prikazana pika za vsako nesrečo, a ni jasno, za kakšno lestvico gre. Tukaj tudi manjkajo države, za katere nimaš podatkov o nesrečah, saj jih v `tabela_1` ni.

Če hočeš primerjeti dva podatka, lahko vsakega prikažeš na svoji osi, npr.

``` R
ggplot(tabela_1, aes(x = PovprecjeBDP/1000, y = Škoda/1e9)) + geom_point()
```

**Comment by valentina2pucer** [comment]
nevem kako bi prikazala..odvisnost BDP od smrti,, in BDP od smrtnih žrtev...pač imela sem idejo da za histogram(BDP) in čez dva grafa, da bi se vidlo to spreminjanje ..zdej najbrž bi morala ostranit tisto kjer kak podatek manjka...
kako bi se dalo to najboljše...?ki ta graf zdej.. se mi zdi koda ne pove kaj dosti

**Comment by jaanos** [comment]
Odvisnost med dvema spremenljivkama najlažje prikažeš tako, da daš vsako spremenljivko na svojo os, kot v zadnjem primeru. Seveda, če iz takega grafa ni kaj dosti videti, lahko to pač pomeni to, da odvisnosti ni.

**Comment by valentina2pucer** [comment]
Če narišem oba grafa, lahko v bistvu rečem, da imata oba (glede na odvisnost od BDP) lognormalno poazdelitev?..ker je zgoščenost v levi in potem kaj iz tega povem?.... da ima nek smisel...
ki če ne nevem kaj bi lahko nardila.

**Comment by valentina2pucer** [comment]
Pri napredni analizi me zanima, ali je vredu, da sem jaz potrdila ta sklepanja... ker glede napovedovanja prihodnosti, nevem kaj bi lahko napovedala...?

**Comment by jaanos** [comment]
Če hočeš videti (linearni) trend med prikazanima spremenljivkama, grafu prištej še `geom_smooth(method = "lm")`. Pri tvojih podatkih kakšnih izrazitih trendov ni videti - nekoliko se pokažejo predvsem zaradi osamelcev (podatkov, ki se preveč razlikujejo od splošnega vzorca in jih lahko razumemo kot izjemne dogodke). Seveda lahko tudi to ugotovitev vključiš v poročilo.

Napovedi za prihodnost pri tebi niso smiselne, saj nimaš primernih podatkov skozi čas. Lahko bi morda naredila združevanje nesreč v skupine - lahko se pokažejo kakšne karakteristike, ki veljajo za posamezno skupino.

**Comment by valentina2pucer** [comment]
ko prištejem to grafu ne deluje..ne v poročilu ne pri analizi

**Comment by valentina2pucer** [comment]
ko dodam to v analizi..mi na grafu naredi.. če vključim še v poročilo, mi ne prevede..kaj moram popravit?

**Comment by jaanos** [comment]
Da nadaljuješ s prištevanjem, mora vsaj plus biti še v prejšnji vrstici.
