### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#17]
ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

želim pushat, do sedaj sem to brez problema, zdaj pa...to

**Comment by jaanos** [comment]
Izgleda, da je nekaj narobe z internetno povezavo. Poskusi še enkrat kasneje.
