### ISSUE TITLE
poročilo

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#18]
pri prevajanju poročila  imam težavo, ker mi noče prevesti zadnjega grafa ..(polje se ne obarva sivo).

**Comment by jaanos** [comment]
Začetek bloka mora biti ves v prvi vrstici - torej pred zavitim zaklepajem ne smeš imeti preloma vrstice (v RStudiu se bo vrstica sicer vseeno prelomila, a se ne bo prikazala številka pred nadaljevanjem vrstice.

Opažam še, da imaš v glavi dokumenta vrstico `runtime: shiny`. Glede na to, da v poročilu ne vključuješ Shiny aplikacije, lahko to vrstico izbrišeš.

**Comment by valentina2pucer** [comment]
aha..  shiny sem dodala, ker imam namen naredit neki še s tem.
