### ISSUE TITLE
shiny

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#19]
Potrebovala bi pomoč, želim namreč pri zemljevidu,ki je že narejen dodati aplikacijo, kjer se bodo z določeno barvo, obarvali določeni predeli glede na gostoto, ki si izbere da ga zanima.(gostota smrtnih žrtev).

**Comment by valentina2pucer** [comment]
v Shiny.r bi rada naredila da mi na zemljevidu pokaže ( obarva ) področja, kjer določena gostota porazdelitve. Pripravila sem primerno tabelo, vendar nevem kako naj napišem podatke, da mi bo pri zemljevidu to upoštevalo.. Na internetu sem našla, da je glede na procente prebivalstva. in je prav funkcija za procente... js sem pa podatke že pripravila, vendar ne vem kam naj jih točno upišem da mi to upošteva

**Comment by jaanos** [comment]
Najprej se opravičujem - sem že napisal odgovor na prvotno sporočilo, a mi ga očitno ni poslalo.

Za Shiny naredi tako:
- premakni vse ukaze `library` iz `shiny.r` v `lib/libraries.r`,
- premakni celoten ukaz `shinyUI` iz `shiny.r` v `shiny/ui.R`,
- premakni celoten ukaz `shinyServer` iz `shiny.r` v `shiny/server.R` (pred njega lahko premakneš še preostalo kodo, ali pa jo daš v katerega od programov, ki ga vključiš s `source`),
- pred `runApp("shiny")` dodaj vse ukaze `source` iz poročila,

V `shiny.r` imaš tako le ukaze `source` in `runApp("shiny")` (stavek `if` lahko pobrišeš) - ko ga zaženeš, se torej zažene tvoj celoten program, nato se pa zažene še Shiny. Tako organizirano aplikacijo lahko potem še vključiš v poročilo, ne da bi bilo potrebno še enkrat zaganjati celotnega programa.

Pazi še na to, da enako poimenuješ komponente v strežniškem in odjemalskem delu. Zemljevidu si v `server.R` dala ime `zem`, zato isto ime uporabi v `ui.R` pri `plotOutput`.

Zemljevida ti sicer ne izriše, ker uporabljaš funkcijo `percent_map`, ki je nimaš v nobenem izmed uvoženih paketov. Da boš lahko podatke sploh risala na zemljevid, namesto razpredelnice `nesrece` izpelji `zem_tabela` iz razpredelnice, kjer imaš že razdelano razdelitev na države, npr. `tabela_1`. Potem lahko zemljevid narišeš na podoben način kot v `vizualizacija.r`:

``` R
    ggplot() + geom_polygon(data = zem_tabela %>%
                              group_by(Lokacija, Razvrstitev) %>%
                              filter(Razvrstitev == input$var) %>%
                              right_join(zem, by = c("Lokacija" = "STATE_NAME")),
                            aes(x = long, y = lat, group = group,
                                fill = Razvrstitev)) +
      scale_fill_manual(values = c("Redko" = "darkgreen",
                                   "Manj gosto" = "black",
                                   "Gosto" = "darkorange",
                                   "Najgosteje" = "darkviolet"),
                        na.value = "darkgrey")
```

Funkcija `scale_fill_manual` omogoča določanje barv za posamezne kategorije. Tako uporaba stavkov `switch` ni potrebna.

**Comment by valentina2pucer** [comment]
Zanima me, kaj mi še manjka, da bo sploh delovalo. + poročila mi noče prevesti (tudi brez shiny), ker je nekaj narobe z zadnjim grafom , ki sem ga dodala.

**Comment by jaanos** [comment]
V `shiny.r` kličeš program `helpers.R`, ki ga nimaš na repozitoriju, tako da to odstrani. Iz `server.R` odstrani še ukaze `source` in stavek `if` ter pri definiciji razpredelnice `zem_tabela` nadomesti `nesrece` s `tabela_1`. Potem lahko Shiny aplikacijo poženeš tako, da poženeš program `shiny.r`.

Poročila ti ne prevede zaradi napake v `analiza.r` - v vrstici 21 premakni `+` v prejšnjo vrstico. Prav tako pri zadnjem grafu v poročilu manjka `+` na koncu tretje vrstice. Da se bo graf prikazal, pobriši presledek med oznako bloka `graf4` in vejico.

**Comment by valentina2pucer** [comment]
sedaj sem popravila pomojem use, vendar še vedno ne deluje shiny .. mi ga ne požene in v poročilu ga tudi ne najde.

**Comment by jaanos** [comment]
V `shiny.r` pokliči še program `analiza/analiza.r`. Da ti bo prevedlo poročilo, spremeni prvi parameter pri `shinyAppDir` na `"shiny"` (to je ime mape, kjer se nahaja aplikacija).
