### ISSUE TITLE
znak ?

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#2]
Zanima me, kako naj odpravim ? , ki se pojavlja v tabeli

**Comment by jaanos** [comment]
Najlažje to narediš z `gsub`:

``` R
nesrece$Lokacija <- gsub("\\?", " ", nesrece$Lokacija)
nesrece$Tip.naravne.nesreče <- gsub("\\?", " ", nesrece$Tip.naravne.nesreče)
nesrece$Dogodek <- gsub("\\?", "-", nesrece$Dogodek)
```

V prvih dveh stolpcih ti vprašaj ustreza presledku, v tretjem pa pomišljaju. Sicer vidim, da so nekateri presledki izginili, tako da lahko te (in tudi vprašaje) popraviš kar v datoteki CSV.
