### ISSUE TITLE
analiza

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#20]
zanima me (tabela_3) zakaj ne deluje koda..želim namreč izbrisati vse tiste vrstice, ki nimajo danem stolpcu flood za podatek

**Comment by jaanos** [comment]
Meni deluje. Sicer pa lahko isto narediš v eni vrstici tako:

``` R
tabela_3 <- nesrece %>% filter(Tip.naravne.nesreče!="Flood") %>% select(-Row)
```

**Comment by valentina2pucer** [comment]
tukaj izbriše vse ki so flood, ne pa različnih..jaz bi ravno obratno.

**Comment by jaanos** [comment]
S pogojem podaš tiste, ki jih želiš ohraniti. Če hočeš torej pustiti samo vrednosti `"Flood"`, zamenjaj `!=` z `==`.

**Comment by valentina2pucer** [comment]
želim dodati stolpec bdp ..zakaj ne morem uporabit kodo kot že prej?..ker ne dela.

**Comment by valentina2pucer** [comment]
mi noče pokazat tabelaBDP...kr bi hotla dodat povprečje..(v odvisnosti od tega tam kjer je flood)

**Comment by jaanos** [comment]
S `select(-Row)` si odstranila stolpec `Row`, tega pa potrebuješ za združevanje. Če torej to odstraniš, bo delovalo.

Sicer pa svetujem, da si pripraviš eno združeno tabelo z vsemi stolpci, raje kot da vsakič znova združuješ. Potem lahko želene stolpce samo izbereš s `select` (za risanje grafov pravzaprav tudi to ni potrebno, saj neuporabljenih stolpcev enostavno nikjer ne uporabiš - s tem ni nič narobe).

**Comment by valentina2pucer** [comment]
nevem zakaj, ampak zdi se mi, da mi npr. pri zadnjem grafu ne naredi pravilno graf glede na podatke iz tabele_3..ker npr. pikica pri prvem i drugem stolpcu bi morala biti enaka.

**Comment by jaanos** [comment]
Glede na to, da imaš tukaj največ en podatek na zvezno državo, lahko odstraniš `position = "jitter"`. Ta namreč nekoliko zamakne pike, kar bi bilo koristno, če bi jih bilo več na enem mestu, tukaj pa ni potrebe po tem.
