### ISSUE TITLE
dodaten stolpec(urejanje)

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#3]
Pri dodatnem stolpcu imam nekaj težav.Želim namreč glede na povprečje dati oznako škodi(nov stolpec). Problem je s podatki o škodi, ki so podani, ne izračuna povprečja....

**Comment by jaanos** [comment]
Za izračun povprečja najprej rabiš številske podatke; če so vmes `NA`-ji, potem lahko funkciji `mean` daš parameter `na.rm = TRUE`. Kolikor vidim, poskušaš računati povprečje iz samih `NA`-jev.
