### ISSUE TITLE
druga tabela

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#4]
pri drugi tabeli imam problem, ker mi oceni npr, da je veliko 600, čeprav sem dala da je z oznako veliko večje od 1000.

**Comment by jaanos** [comment]
V stolpcu `Fatalities` nimaš številskih podatkov. Najprej bo treba z `gsub` pobrisati vejice in ostalo besedilo (kjer imaš dve številki, se boš morala odločiti, katero uporabiti), potem pa dobljena števila pretvoriti z `as.numeric`. Šele potem lahko delaš primerjave.
