### ISSUE TITLE
tabela1

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#5]
kako naj v drugem stolpcu dam, da mi izbriše vse druge št.kjer se nahajajo(drugi stolpec), ohranila bom samo prvo cifro za podatek.

**Comment by jaanos** [comment]
Najlažje bo, da pobereš vse številke na začetku niza, pa jih takoj še pretvoriš v števila:

``` R
tabela1$Fatalities<-strapplyc(tabela1$Fatalities, "^([0-9]+)") %>% unlist() %>% as.numeric()
```

Mimogrede, program se ti ustavi, ko kličeš `nrow(tabela)`, saj spremenljivka `tabela` ni definirana - tukaj hočeš `tabela1`. Poleg tega bo treba upoštevati tudi primer, ko velja `Fatalities == 1000`, sicer v tem primeru (ki se dejansko pojavi) dobiš `NA`.
