### ISSUE TITLE
Graf

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#6]
Potrebovala bi pomoč pri izdelavi grafa(pita). Del sem si pomagala z internetom, ampak nevem kako naj zapišem, da bi mi: tabela1, glede na tretji stolpec , razmerje med obema oznakama smrtnih žrtvem(torej dve barvi v tortnem prikazu)

**Comment by jaanos** [comment]
`pie3D` pričakuje kot vhod vektor s pogostostmi posameznih vrednosti - tega lahko dobiš s funkcijo `table`. Tako lahko rišeš

``` R
pie3D(table(slices), labels=lbls, explode=0.15, start=1.5,
      labelrad=1.18, labelcex=1, main='Tortni diagram')
```

Ta ukaz hočeš sicer izvesti v poročilu, da bo graf na pravem mestu, saj `pie3D` ne deluje kot `ggplot` in direktno nariše graf.

Ukaza `dev.off()` ne potrebuješ - ta je namenjen končanju risanja npr. v datoteko PDF. Ker tega ne počneš (oziroma bo pri poročilu za to zadolžen RMarkdown), ta ukaz pobriši.

**Comment by valentina2pucer** [comment]
Popravila sem, vendar mi grafa še vedno ne nariše.
Čeprav sem namestila potreben paket mi napiše:object 'pie3D' not found

**Comment by jaanos** [comment]
Če prav razumem, si torej namestila knjižnico plotrix in jo naložila z ukazom `library(plotrix)`. Poglej, katero verzijo knjižnice plotrix imaš - to dobiš z ukazom `packageVersion("plotrix")`? Pri meni izpiše `3.5.12`.

Če ne bi šlo, lahko tortni diagram (ki pa ne bo tridimenzionalen) narišeš tudi z ggplot2:

``` R
ggplot(tabela1, aes(x=factor(1), fill=Stopnja_smrti)) + geom_bar(width=1) +
  coord_polar(theta = "y") + xlab("") + ylab("")
```

**Comment by valentina2pucer** [comment]
3.6 različica

**Comment by valentina2pucer** [comment]
deluje.. sem ponovno naložila paket
