### ISSUE TITLE
Poročilo

### ISSUE THREAD

**Issue by jaanos** [valentina2pucer/APPR-2015-16#7]
Poročila ti ne prevede, ker se v njem sklicuješ na spremenljivke iz vzorca. Najbolje bo, če del iz vzorca pobrišeš oziroma ga nadomestiš s svojimi podatki.

Da ti v poročilo ne bo izpisovalo obvestil ob uvozu knjižnic, vse klice ukazov `library` in `require` premakni iz `uvoz/uvoz.r` v `lib/libraries.r`. Druga možnost bi bila, da pri bloku, kjer kličeš `uvoz.r`, nastaviš `results='hide'` in `message=FALSE`, da se ta obvestila ne izpisujejo.

Grafa ne riši v programu `uvoz.r`, pač pa v ustrezno postavljenem bloku kode v poročilu. Ker `pie3D` neposredno nariše graf, bo torej treba ta ukaz premakniti v poročilo.

**Comment by valentina2pucer** [comment]
kako moram točno zapisati ta graf, ker mi ne dela še vedno pri poročilo, drugače pa mi ga nariše

**Comment by jaanos** [comment]
Obstoječi ukaz `pie3D` premakni v poročilo, npr. namesto histograma iz vzorca:

``````
```{r torta, echo=FALSE, fig.align='center', fig.cap='Tortni diagram'}
pie3D(table(slices), labels=lbls, explode=0.15, start=1.5, labelrad=1.18, labelcex=1, main='Tortni diagram')
```
``````

**Comment by valentina2pucer** [comment]
to sem popravila sedaj, ampak še vedno mi ne prevaja poročila.

**Comment by jaanos** [comment]
Bloku kode, kjer uvažaš knjižnice (takoj pod glavo), si odstranila oznako, da gre za blok kode; prav tako si odstranila blok kode, kjer kličeš `uvoz.r`. V resnici lahko oba tudi združiš, tako da naj bo pod glavo tako:

``````
```{r setup, echo=FALSE, results='hide', message=FALSE}
source("lib/libraries.r", encoding = "UTF-8")
source("uvoz/uvoz.r", encoding = "UTF-8")
```
``````

Poleg tega si pobrisala presledke za dvopičji v glavi pri `title` in `author` - med `:` in `"` mora biti v obeh vrsticah presledek.

**Comment by pustotnk** [comment]
sedaj mi še vedno ne dela, čeprav sem popravila

**Comment by valentina2pucer** [comment]
popravila sem vendar še vedno ne deluje

**Comment by jaanos** [comment]
Kaj točno ne deluje? Meni prevede tvoje poročilo v PDF, tako da bom dodal povezavo do tvojega projekta. Če boš še kaj spreminjala, mi prosim javi, da posodobim povezavo.

Če nimaš nameščenega LaTeXa, ti prevajanje v PDF ne bo delovalo. V tem primeru lahko prevedeš v HTML, a vseeno svetujem, da si namestiš LaTeX.

Ena pripomba: sedaj se ti v poročilu izpiše vrstica, kjer si klicala `uvoz.r`, a si odstranila oznake bloka kode (vrstica 28). To seveda izbriši, da se ne bo izpisovalo v poročilu.

**Comment by valentina2pucer** [comment]
LATEX imam nameščen, tako da ne vem kje bi biu problem. Tisto sem izbrisala tako da bi moglo bit v redu. Edino še en graf imam dodaten ki ga bi magari pokazala v uvozu, ampak bi ga rabla še dodelat.
kaj bi mogla pa potem nardit za naprej, da mi bo delovalo, glede na to da latex je gor

**Comment by jaanos** [comment]
Kaj natančno pa ti javi? Ali ti prevede v HTML?

Iz `uvoz.r` seveda odstrani risanje obeh grafov in ju prikaži v poročilu.

**Comment by valentina2pucer** [comment]
ko sem vključila še drugi graf, mi pri prevajanju javi napako

Quitting from lines 55-57 (projekt.Rmd) 
Error in eval(expr, envir, enclos) : object 'False' not found
Calls: <Anonymous> ... process_group.block -> call_block -> eval_lang -> eval -> eval
Execution halted

**Comment by jaanos** [comment]
Pri zadnjem bloku kode namesto `echo = False` napiši `echo = FALSE`.

**Comment by valentina2pucer** [comment]
Sedaj bi moglo delat, meni ne prevede, ker mi napiše:
Enter file name: 
! Emergency stop.
<read *> 

l.12     \usepackage

pandoc.exe: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS projekt.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output projekt.pdf --template "C:\Users\valentina\Documents\R\win-library\3.2\rmarkdown\rmd\latex\default.tex" --highlight-style tango --latex-engine xelatex --include-in-header "lib\styles.sty" --variable "geometry:margin=1in"' had status 43 
Execution halted

odpre se mi okno za nek paket inštalirat, vendar mi ga noče

**Comment by valentina2pucer** [comment]
Sedaj ko sm napisala FALSE.. MI noče push-at
To git@github.com:valentina2pucer/APPR-2015-16.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:valentina2pucer/APPR-2015-16.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by jaanos** [comment]
Najprej naredi pull - očitno nimaš zadnje verzije pr sebi.
