### ISSUE TITLE
tabela v poročilu

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#8]
zanima me kako naj tabeli na x osi priredim ustrezne podatke. sedaj so oznake 1,2,3..itd. želela pa bi pripadajoče letnice. Malo težje mi je, ker poročila nimam pred sabo, ker mi ne odpira, samo vem da morem to popravit.

**Comment by jaanos** [comment]
Oznake so številke, ker jih črpaš iz imen vrstic razpredelnice `tabela1`, a teh nisi nikjer podala. Če bi k `names.arg` podala podatke iz stolpca `Year`, bi se ti izpisala leta.

Sicer pa raje kot `barplot` uporabi `ggplot`. Glede na to, da se ti nekatera leta ponovijo, lahko narediš nekaj takega:

``` R
ggplot(tabela1 %>% group_by(Year) %>% summarise(Fatalities = sum(Fatalities)) %>%
         filter(Fatalities >= 600),
       aes(x = reorder(Year, Fatalities), y = Fatalities)) + geom_bar(stat = "identity") +
  coord_flip() + xlab("Year")
```

Tukaj torej najprej združiš (`group_by`) po letih in izračunaš skupno število žrtev (`summarise`), potem pa izbereš (`filter`) samo tista leta, ko je bilo vsaj 600 žrtev. Z `reorder` potem poskrbiš, da se ti leta izpišejo po vrsti glede na število žrtev (ker imaš številsko spremenljivko, bi ti sicer naredilo en stolpec za vsako leto - tudi za manjkajoča). Lahko pa seveda enostavno narišeš črtni graf skozi leta:

``` R
ggplot(tabela1 %>% group_by(Year) %>% summarise(Fatalities = sum(Fatalities)),
       aes(x = Year, y = Fatalities)) + geom_line()
```

Če ti poročila ne prevede, lahko vseeno poženeš vso kodo v njem tako, da zgoraj desno pod _Chunks_ izbereš _Run All_. Če pri tem pride do napake, jo je seveda potrebno odpraviti, da ti bo poročilo prevedlo. V nasprotnem primeru imaš naložene vse podatke, pa lahko potem iz njih rišeš grafe v RStudiu.

**Comment by valentina2pucer** [comment]
kako pa bi naredila, da mi y os kjer so letnice, da po letih po vrsti.. od najstarejšega leta do najmlajšega  npr

**Comment by jaanos** [comment]
Če hočeš, da ti prikaže stolpce samo za tista leta, ki jih imaš, lahko pri `aes` podaš parameter `x = factor(Year)`.

**Comment by valentina2pucer** [comment]
uporabila sem prvo kodo, kjer to ne deluje

**Comment by jaanos** [comment]
Če poženem tvoja programa `libraries.r` in `uvoz.r`, mi zgornja koda deluje? Kaj si pa ti naredila? Lahko tudi naložiš zadnjo verzijo na GitHub, če imaš že vključeno v svoji kodi.

**Comment by valentina2pucer** [comment]
aes(x = reorder(Year, Fatalities), y = Fatalities)) + geom_bar(stat = "identity") +
Error: unexpected ')' in "aes(x = reorder(Year, Fatalities), y = Fatalities))"

> coord_flip() + xlab("Year")
> Error in coord_flip() + xlab("Year") : 
>   non-numeric argument to binary operator

**Comment by valentina2pucer** [comment]
to mi napiše da ni vredu

**Comment by jaanos** [comment]
Tukaj izgleda, kot da si izvedla samo zadnji dve vrstici. Preglej, če imaš morda v prvih dveh vrsticah kak oklepaj preveč.
