### ISSUE TITLE
zemjevid

### ISSUE THREAD

**Issue by valentina2pucer** [valentina2pucer/APPR-2015-16#9]
zanima me glede zemljevida:
želela bi uvoziti iz  
http://wiki.potnik.si/images/thumb/2/27/zemljevid_Zdru%C5%BEenih_dr%C5%BEav_Amerike.gif/500px-zemljevid_Zdru%C5%BEenih_dr%C5%BEav_Amerike.gif

in potem glede na tabelo nesrece , 2.stolpec lokacija , po zemljevidu označiti dana imena ki se pojavijo.

**Comment by jaanos** [comment]
Zemljevid ni samo slika - gre za skupek natančnih informacij o oblikah, ki določajo območja, skupaj z morebitnimi dodatnimi podatki. Zemljevid, ki ga uvoziš, mora biti v obliki Shapefile. Če potrebuješ zemljevid ZDA, lahko uporabiš [tistega](http://baza.fmf.uni-lj.si/states_21basic.zip), ki smo ga uporabili v [primeru](https://ucilnica.fmf.uni-lj.si/mod/resource/view.php?id=17641) z vaj, ki je na voljo na spletni učilnici.

Če hočeš povezati posamezne nesreče z zveznimi državami, bo najbolje, če si pripraviš tabelo, ki za vsako nesrečo (priredili ji bomo zaporedno številko) pove, na katere zvezne države se nanaša. Potem lahko tabeli združiš. Z zgornjim zemljevidom in stolpcem `Location` v `tabela1` bi šlo nekako takole:

``` R
tabela1$Row <- 1:nrow(tabela1)
drzave.nesrece <- lapply(zda$STATE_NAME, function(x) {
  r <- grep(x, tabela1$Location)
  return(data.frame(State = rep(x, length(r)), Row = r))
}) %>% bind_rows() %>% as.data.frame()
zdruzena.tabela <- inner_join(tabela1, drzave.nesrece, by = "Row")
```

Za vsako zvezno državo torej poiščeš, pri katerih nesrečah se nahaja, ter pripraviš razpredelnico z imenom zvezne države in številko vrstice (te dobiš iz `grep`), nato pa z `bind_rows()` dobljene razpredelnice združiš v eno. Potem lahko z `inner_join` obe razpredelnici združiš - v dobljeni razpredelnici se bo vsaka nesreča pojavila toliko krat, kolikor je navedenih zveznih držav.

Sedaj lahko narišeš npr. zemljevid, ki prikazuje skupno število žrtev za vsako zvezno državo (uporabiš funkcijo `pretvori.zemljevid` iz zgornjega primera):

``` R
zem <- pretvori.zemljevid(zda)
ggplot() + geom_polygon(data = zdruzena.tabela %>% group_by(State) %>%
                          summarise(Fatalities = sum(Fatalities)) %>%
                          right_join(zem, by = c("State" = "STATE_NAME")),
                        aes(x = long, y = lat, group = group, fill = Fatalities))
```

Podobno kot v #8 najprej izračunaš skupno število žrtev za vsako zvezno državo, nato pa podatke združiš z zemljevidom. Zaradi `right_join` bodo v zemljevidu ostale zvezne države, ki se ne pojavijo med tvojimi podatki.

**Comment by valentina2pucer** [comment]
ko zemljevid uvozim, tabela ki jo na novo nardim je brez podatkov

**Comment by valentina2pucer** [comment]
am ma jaz pišem za uvoz zemljevida pri : vizualizacija.r
ali morem cel zemljevid pri uvoz.r.

**Comment by jaanos** [comment]
V `uvoz.r`, ko uvoziš razpredelnico `tabela1`, iz nje pobrišeš stolpec `Location`. Če tega ne narediš, se bo razpredelnica `drzave.nesrece` napolnila.

Zemljevid imaš lahko v `vizualizacija.r`. Seveda bo treba to datoteko vključiti v poročilo, ko boš vanj dodala grafe in zemljevide na podlagi tam izračunanih podatkov.

**Comment by valentina2pucer** [comment]
sedaj sem popravila to, tako da sem zakomentirala, vendar se ta tabela ni še vedno napolnila in niti zdruzena.tabela se ni

**Comment by valentina2pucer** [comment]
deluje....
